name: Issue Templates

description: This configuration file sets up the issue templates for the repository.

labels:
  - bug
  - feature

template:
  - name: Bug Report
    description: Use this template to report a bug.
    title: "[BUG] "
    body:
      - type: markdown
        attributes:
          value: "Please describe the bug you encountered."
      - type: input
        id: steps_to_reproduce
        attributes:
          label: "Steps to reproduce"
          description: "List the steps to reproduce the bug."
      - type: input
        id: expected_behavior
        attributes:
          label: "Expected behavior"
          description: "What did you expect to happen?"
      - type: input
        id: actual_behavior
        attributes:
          label: "Actual behavior"
          description: "What actually happened?"

  - name: Feature Request
    description: Use this template to request a new feature.
    title: "[FEATURE] "
    body:
      - type: markdown
        attributes:
          value: "Please describe the feature you would like to request."
      - type: input
        id: feature_description
        attributes:
          label: "Feature description"
          description: "What is the feature you want to request?"
      - type: input
        id: benefits
        attributes:
          label: "Benefits"
          description: "What are the benefits of this feature?"
      - type: input
        id: additional_context
        attributes:
          label: "Additional context"
          description: "Any additional context or information."